#!/bin/bash
#
# Copyright (c) 2010, Aaron Dewes <aaron.dewes@web.de>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the project nor the
#    names of its contributors may be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER ''AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

function test_file {
    file="${1}"

    # Something close to our style which is the same as the Qt4 code style
    #astyle --indent=spaces=4 --brackets=linux --indent-labels --pad=oper --unpad=paren --one-line=keep-statements --convert-tabs --indent-preprocessor `find -type f -name '*.cpp'` `find -type f -name '*.h'`

    echo "--Checking style--"
        tempfoo=`basename $0`
        newfile=`mktemp /tmp/${tempfoo}.XXXXXX` || exit 1
        astyle --indent=spaces=4 --brackets=linux --indent-labels --pad=oper --one-line=keep-statements --convert-tabs --indent-preprocessor < $file > $newfile 2>> /dev/null
        diff "${file}" "${newfile}"
        r=$?
        rm "${newfile}"
        if [ $r != 0 ] ; then
            echo "Code style error in $file, please fix before commiting."
            exit 1
        fi
    echo "--Checking style pass--"
}

case "${1}" in
    --about )
        echo "Check that the code follows a consistent code style."
        ;;
    * )
        astyle --version 2>> /dev/null
        if [ $? -eq 127 ] ; then
            echo "--AStyle not found installed on the system, skiping style check"
            exit 0;
        fi

        for file in `git diff-index --cached --name-only HEAD | grep *.cpp` ; do
            test_file "${file}"
        done
        ;;
esac
