#!/bin/bash
./generateAuthors 0.5..HEAD | while read line
do
        name=`echo $line | sed -e 's/ [^ ]*@[^ ]*//g'`
        email=`echo $line | sed -e 's/.* //g' | tr [A-Z] [a-z]`
        echo -n "<img alt=\"$name\"src=\"https://secure.gravatar.com/avatar/"
        # OS X
        #md5=`md5 -s $email | md5sum`
        # Linux
        md5=`echo -e "$email\c" | md5sum | sed -e s/\ -//g`
        echo -n $md5
        echo -n ".jpg?s=40\" width=\"40\" height=\"40\" />";
        echo "$name $email<br>"
done

