.TH ARORA-CACHEINFO "1" "July 2009"

.SH NAME
arora-cacheinfo - a tool for extracting files and metadata out of Arora cache files.

.SH SYNOPSIS
.B arora-cacheinfo [-o cachefile] [file | url]

.SH DESCRIPTION
.B Arora-cacheinfo
is a tool for extracting files and displaying metadata out of an Arora cache files that are stored on the disk.  Every cache file contains both the cached file (sometimes compressed) and metadata associated with it such as expiration date.  Cache files names always include the md5sum of the url and passing a url to arora-cacheinfo.1 will automatically determine the correct matching cache file name.

.SH OPTIONS
.TP
.B -o cachefile
Write the cached file if it exists to \fBcachefile\fR
.TP
.B file
Specify the file to read from.
.TP
.B url
Specify the url from which to compute the file to read from.
.TP

.SH BUGS
Please report bugs to \fIhttp://code.google.com/p/arora/issues/list\fR.

.SH AUTHOR
The author of arora-cacheinfo is Benjamin C. Meyer <ben@meyerhome.net>.
.PP
This manual page was written by Benjamin C. Meyer <ben@meyerhome.net>
.PP
Permission is granted to copy, distribute and/or modify this document under the
terms of the
GNU General Public License, Version 2 or any later version published by the Free
Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be
found in /usr/share/common-licenses/GPL.
