.TH HTMLTOXBEL "1" "July 2009"

.SH NAME
arora-placesimport - a tool for importing browser history from Firefox 3 and up

.SH SYNOPSIS
.B arora-placesinfo ~/.mozilla/firefox/[profile-dir]/places.sqlite

.SH DESCRIPTION
.B htmlToXBel
is a tool for importing browser history from Firefox 3 and up.

.SH BUGS
Please report bugs to \fIhttp://code.google.com/p/arora/issues/list\fR.

.SH AUTHOR
The author of htmlToXBel is Benjamin C. Meyer <ben@meyerhome.net>.
.PP
This manual page was written by Benjamin C. Meyer <ben@meyerhome.net>
.PP
Permission is granted to copy, distribute and/or modify this document under the
terms of the
GNU General Public License, Version 2 or any later version published by the Free
Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be
found in /usr/share/common-licenses/GPL.
