#!/bin/sh
#
# A simple test to prevent work on Arora during the work day.

# If it is the weekend, bail out
day=`date +%w`
# Saturday
if [ $day -eq 6 ] ; then
  exit 0
fi
# Sunday
if [ $day -eq 0 ] ; then
  exit 0
fi

# if it is a weekday check the time
hour=`date +%H`
if [ $hour -ge 8 ] ; then
  if [ $hour -le 17 ] ; then
    echo "Go back to work."
    exit 1
  fi
fi
exit 0
