#!/bin/bash
#
# Check the files that are being commited with the bash grep style checker
#
dir=`dirname $0`
for file in `git diff-index --name-only HEAD | grep .cpp` ; do
    echo "--checking style via bash hack: $file"
    $dir/findstyleerrors.sh $file
done
exit 0
