#!/bin/sh
#
# Wherever you are make sure something builds.
#
# Feel free to bypass this if the current commit doesn't match the current state.

echo "--Attempting to build--"
make --quiet
if [ $? != 0 ] ; then
    echo "--Build failed, fix failure before commiting--";
    exit 1
fi
echo "--Attempting to build pass--"

