.TH ARORA "1" "May 2008"

.SH NAME
Arora - Lightweight web browser based on Qt and WebKit

.SH SYNOPSIS
.B arora

.SH DESCRIPTION
.B Arora
is a lightweight, cross-platform web browser using the Qt 4.4 port of the WebKit
layout engine. It is based on the demo browser application shipped with Qt
demos.
.PP
.B Arora
cannot be used from the command line, as it is Qt-based software.
Please run it under X.

.SH OPTIONS
.B Arora
has no options.

.SH BUGS
Please report bugs to \fIhttp://code.google.com/p/arora/issues/list\fR.

.SH AUTHOR
Arora is developed by Benjamin C. Meyer <ben@meyerhome.net>, based on code release by Trolltech ASA.
.PP
This manual page was written by Matvey Kozhev <sikon@ubuntu.com> for the Ubuntu system (but may be used by others).
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU General Public License, Version 2 or any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
