.TH ARORA "1" "May 2008"

.SH NAME
Arora - Lightweight web browser based on Qt and WebKit

.SH SYNOPSIS
.B arora [Qt options] [url]

.SH DESCRIPTION
.B Arora
is a lightweight, cross-platform web browser using the Qt 4.4 port of the WebKit
layout engine. It is based on the demo browser application shipped with Qt
demos.

.SH OPTIONS
.SS Common Qt Options
.TP
.B -style style, -style=style
Specify the Qt widget style to use (examples: plastique, cleanlooks).
.TP
.B -stylesheet stylesheet, -stylesheet=stylesheet
Specify the user stylesheet to use when rendering widgets.
.TP
.B -session session, -session=session
Restore the application from an earlier \fBsession\fR.
.TP
.B -widgetcount
Print a debug message at the end about the number of widgets left undestroyed
and the maximum number of widgets that existed at the same time.
.TP
.B -reverse
Sets the application's layout direction to right-to-left.

.SS Options Specific to Arora
.TP
.B url
The URL address to open in the browser.

.SH BUGS
Please report bugs to \fIhttp://code.google.com/p/arora/issues/list\fR.

.SH AUTHOR
The author of Arora is Benjamin C. Meyer <ben@meyerhome.net>.
.PP
This manual page was written by Matvey Kozhev <sikon@ubuntu.com>.
.PP
Permission is granted to copy, distribute and/or modify this document under the
terms of the
GNU General Public License, Version 2 or any later version published by the Free
Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be
found in /usr/share/common-licenses/GPL.
