name: Build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Prepare for 20.10
      run: sudo bash -c 'echo "Prompt=normal" >> /etc/update-manager/release-upgrades'
    - name: Update to 20.10
      run: sudo apt update && sudo apt upgrade && sudo do-release-upgrade

    - name: Install dependencies
      run: sudo apt install -y qtwebengine5-dev libqt5webkit5-dev qtbase5-dev qtbase5-dev-tools qtscript5-dev qttools5-dev qt5-default

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
